# version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - my-network
    volumes:
      - zookeeper-storage:/var/lib/zookeeper/data
      
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    command: >
      sh -c "rm -f /kafka/meta.properties && start-kafka.sh"
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" 
      KAFKA_ADVERTISED_HOST_NAME: kafka 
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092 
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka  
    depends_on:
      - "zookeeper"
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 5s
      retries: 50
      start_period: 1s
      timeout: 1s

  mysql:
    image: mysql
    container_name: mysql_container
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: sim
      MYSQL_PASSWORD: sim44
      MYSQL_DATABASE: sephora_container
    volumes:
      - ./data/database:/var/lib/mysql  
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mysql", "-u", "sim", "-psim44", "-e", "SHOW DATABASES;"]
      interval: 5s
      retries: 50
      start_period: 1s
      timeout: 1s

  receiver:
    deploy:
      replicas: 3
    # image: sim4444/receiver:latest
    # pull_policy: always
    build:
      context: ./receiver
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    volumes:
      - ./config/prod/receiver:/app/config
      - ./logs/receiver:/app/logs
    depends_on:
      - kafka
    networks:
      - my-network
    restart: always

  storage:
    # image: sim4444/storage:latest
    # pull_policy: always
    build:
      context: ./storage
      dockerfile: Dockerfile
    volumes:
      - ./config/prod/storage:/app/config
      - ./logs/storage:/app/logs
    # ports:
    #   - "8090:8090"
    environment:
      DB_HOST: mysql/
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_healthy       
    networks:
      - my-network
    restart: always

  processing:
    # image: sim4444/processing:latest
    # pull_policy: always
    build:
      context: ./processing
      dockerfile: Dockerfile
    environment:
      CORS_ALLOW_ALL: "no"
    ports:
      - "8100:8100"
    volumes:
      - ./config/prod/processing:/app/config
      - ./logs/processing:/app/logs
      - ./data/processing:/app/data
    depends_on:
      - storage
    networks:
      - my-network
    restart: always

  analyzer:
    # image: sim4444/analyzer:latest 
    # pull_policy: always
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    environment:
      CORS_ALLOW_ALL: "no"
    ports:
      - "8200:8200"
    volumes:
      - ./config/prod/analyzer:/app/config
      - ./logs/analyzer:/app/logs
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - my-network
    restart: always

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./dashboard/default.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - receiver
      - analyzer
      - processing
      - storage
    networks:
      - my-network
    restart: always

  consistency_check:
      build:
        context: ./consistency_check
      volumes:
        - ./config/prod/consistency_check:/app/config
        - ./logs/consistency_check:/app/logs
        - ./data/consistency_check:/app/data
      expose:
       - "8300"
      depends_on:
        - analyzer
        - storage
        - processing
      networks:
        - my-network
      restart: always

      
networks:
  my-network:
    driver: bridge

volumes:
  zookeeper-storage: 